name: 'Together JavaScript Action'
description: 'github javascript action to help run actions with other repositories PRs mentioned in description'
inputs:
  myToken: # GITHUB_TOKEN
    description: 'GITHUB_TOKEN for interacting with octokit client'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
